#!/usr/bin/env python
import re, argparse
from itertools import chain
""" Ioan (IsOform ANnotator) """


from revanno import add_parser_revanno
from anno import add_parser_anno
from codonsearch import add_parser_codonsearch
from codoneq import add_parser_codoneq


if __name__ == '__main__':

    parser = argparse.ArgumentParser(description=__doc__)

    subparsers = parser.add_subparsers()
    add_parser_revanno(subparsers)
    add_parser_anno(subparsers)
    add_parser_codoneq(subparsers)
    add_parser_codonsearch(subparsers)

    args = parser.parse_args()
    args.func(args)
