#!/usr/bin/env python
import re, argparse
from itertools import chain
""" Ioan (IsOform ANnotator) """


from codonanno import add_parser_codonanno
from nucanno import add_parser_nucanno
from codonsearch import add_parser_codonsearch
from codoneq import add_parser_codoneq


if __name__ == '__main__':

    parser = argparse.ArgumentParser(description=__doc__)

    subparsers = parser.add_subparsers()
    add_parser_codonanno(subparsers)
    add_parser_nucanno(subparsers)
    add_parser_codoneq(subparsers)
    add_parser_codonsearch(subparsers)

    # psr_infrtrns = psrs.add_parser('infer.transcript', help='infer transcript from nucleotide and amino acid position')

    args = parser.parse_args()
    args.func(args)

